#!/bin/bash
# ==============================================================================
# Caffe 项目复盘分析脚本
# 输出模块演进路线、关键文件清单、测试对标关系
# ==============================================================================
set -e

echo "=============================================="
echo "  Caffe 项目复盘分析"
echo "=============================================="
echo ""

echo "=== 模块演进路线 ==="
echo ""
echo "  caffex/python/ (废弃)  --→  python/ (主力维护)"
echo "      │                            │"
echo "      │ 原始 BVLC PyCaffe          │ caffeproto/ + operators/ + protos/"
echo "      │ (Makefile 构建)            │ + scripts/ + tests/"
echo "      │                            │ 新架构：caffeproto 解耦"
echo "      │                            │ operators 独立、测试完善"
echo "      │                            │"
echo "      └────── 测试对标 ────────────→  python/pycaffe/python/pycaffe/"
echo "                                    │ PyCaffe 模块"
echo "                                    │ scikit-build-core + CMake"
echo "                                    │ 测试对标：caffex/python 结果"
echo ""

echo "=== 关键文件清单 ==="
echo ""
echo "  [废弃] caffex/python/caffe/"
echo "    ├── __init__.py          - 模块入口"
echo "    ├── _caffe.cpp           - C++ Python 绑定"
echo "    ├── pycaffe.py           - 核心 API (Net, Solver)"
echo "    ├── classifier.py        - 分类器"
echo "    ├── detector.py          - 检测器"
echo "    ├── draw.py              - 网络可视化"
echo "    ├── io.py                - 数据 IO"
echo "    ├── net_spec.py          - 网络规格"
echo "    ├── coord_map.py         - 坐标映射"
echo "    ├── proto/               - protobuf 生成文件"
echo "    └── test/                - 测试 (test_net.py, test_solver.py, ...)"
echo ""
echo "  [主力] python/"
echo "    ├── caffeproto/          - caffe_pb2 封装"
echo "    │   ├── __init__.py"
echo "    │   ├── caffe_fuse.py"
echo "    │   └── caffe_utils.py"
echo "    ├── operators/           - TVM Relax 算子"
echo "    │   ├── __init__.py"
echo "    │   └── layers.py (L2Norm)"
echo "    ├── protos/              - protobuf 源文件"
echo "    │   ├── caffe.proto"
echo "    │   └── caffe_pb2.py"
echo "    ├── scripts/             - 工具脚本"
echo "    │   ├── gen_proto.py"
echo "    │   ├── run_test.sh"
echo "    │   ├── _check_python.sh"
echo "    │   ├── _diag.sh"
echo "    │   └── test_new_features.sh"
echo "    ├── tests/               - 测试"
echo "    │   ├── verify.py"
echo "    │   ├── test_inference.py"
echo "    │   └── test_l2norm.py"
echo "    └── pycaffe/             - PyCaffe 构建"
echo "        ├── CMakeLists.txt"
echo "        ├── pyproject.toml"
echo "        ├── build.sh"
echo "        ├── lenet_deploy.prototxt"
echo "        └── python/pycaffe/  - PyCaffe 源码"
echo "            ├── __init__.py"
echo "            ├── _caffe.cpp"
echo "            ├── pycaffe.py"
echo "            ├── classifier.py"
echo "            ├── detector.py"
echo "            ├── draw.py"
echo "            ├── io.py"
echo "            ├── net_spec.py"
echo "            └── coord_map.py"
echo ""

echo "=== 测试对标关系 ==="
echo ""
echo "  旧 caffex/python/caffe/test/   →   新 pycaffe 镜像验证"
echo "  ─────────────────────────────────────────────────────"
echo "  test_net.py  (TestNet)          →  Net 创建/前向/反向/保存/加载"
echo "  test_net.py  (TestLevels)       →  Level 过滤行为"
echo "  test_net.py  (TestStages)       →  Stage 过滤行为"
echo "  test_net.py  (TestAllInOne)     →  多阶段全功能"
echo "  test_solver.py                  →  Solver 行为"
echo "  test_coord_map.py               →  coord_map 模块"
echo "  test_draw.py                    →  draw 模块"
echo "  test_io.py                      →  io 模块"
echo ""

echo "=== Docker 镜像依赖关系 ==="
echo ""
echo "  caffe-cpu:python-module  (基础镜像：Caffe 编译 + python/ 模块)"
echo "       │"
echo "       └──→  caffe-cpu:pycaffe  (PyCaffe wheel 镜像)"
echo ""

echo "=== 构建命令 ==="
echo ""
echo "  # 一键构建全部"
echo "  make -C docker/modules all"
echo ""
echo "  # 单独构建"
echo "  make -C docker/modules python-module"
echo "  make -C docker/modules pycaffe"
echo ""
echo "  # 仅分析"
echo "  make -C docker/modules analyze"
echo ""

echo "=============================================="
echo "  复盘分析完成"
echo "=============================================="