[program:jupyter]
user=caffe-origin
command=jupyter notebook --config=/home/caffe-origin/.jupyter/jupyter_notebook_config.py
directory=/workspace
autorestart=true
startretries=3
priority=200
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisor/jupyter-stderr.log
stderr_logfile_maxbytes=1048576
redirect_stderr=false
environment=HOME="/home/caffe-origin",USER="caffe-origin",LANG="zh_CN.UTF-8",LC_ALL="zh_CN.UTF-8",CAFFE_ROOT="/workspace/caffex",PATH="/workspace/caffex/build/tools:/usr/local/bin:/usr/bin:/bin",LD_LIBRARY_PATH="/workspace/caffex/build/lib:/usr/lib:/usr/lib/x86_64-linux-gnu:/usr/local/lib",PYTHONPATH="/workspace/caffex/python"
