name: caffe-ffi
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python>=3.14
  - cmake>=3.26
  - ninja>=1.13
  - cxx-compiler
  - m2w64-gcc  # [win]
  - libprotobuf>=7.0.0
  - protobuf>=7.0.0
  - libopenblas
  - openblas
  - pip
  - pip:
      - scikit-build-core>=0.10
      - numpy>=2.3
      - apache-tvm-ffi
      - pytest>=8.0
